/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/golemModelPortfolio.glb --transform 
Files: public/models/golemModelPortfolio.glb [11.31MB] > C:\Users\Sahil\OneDrive\Documents\Desktop\ProjectsREsume\New folder\golemModelPortfolio-transformed.glb [553.24KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/golemModelPortfolio-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.input.geometry} material={materials['material_0.001']} position={[0, 0.547, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/golemModelPortfolio-transformed.glb')
